name: Admin-BUILD

on: 
    push:
        branches: ["main"]

env: 
    LOGIN: ${{secrets.DOCKER_LOGIN}}
    PASSWORD: ${{secrets.DOCKER_PASSWORD}}
    SERVER_NAME: ${{secrets.DOCKER_SERVER_NAME}}

jobs:
    server_build: 
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: server
        steps:
            - uses: actions/checkout@master
            - name: login to docker
              run: |
                docker login -u ${{env.LOGIN}} -p ${{env.PASSWORD}}
            - name: build image
              run: docker build -t ${{env.LOGIN}}/${{env.SERVER_NAME}}:deploy -f Dockerfile .
            - name: push build
              run: docker push ${{env.LOGIN}}/${{env.SERVER_NAME}}:deploy